/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingFactory } from "./VotingFactory";
export * as factories from "./factories";
export { VotingFactory__factory } from "./factories/VotingFactory__factory";
